#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

enable_color_support() {

    if [[ $COLORTERM == gnome-* && $TERM == xterm ]] \
        && infocmp gnome-256color &> /dev/null; then
        export TERM="gnome-256color"
    elif infocmp xterm-256color &> /dev/null; then
        export TERM="xterm-256color"
    fi

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Load OS specific color support.

    . "colors/$OS/bash_colors"

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# [!] Don't break this function into smaller, more specialized ones
# as you will only pollute the global space even more. This function
# cannot be unset because it's called every time the prompt string
# is shown.

get_git_repository_details() {

    local branchName=""
    local tmp=""

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Check if the current directory is in a Git repository.

    ! git rev-parse &>/dev/null \
        && return

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Check if in `.git/` directory (some of the following
    # checks don't make sense/won't work in the `.git` directory).

    [ "$(git rev-parse --is-inside-git-dir)" == "true" ] \
        && return

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Check for uncommitted changes in the index.

    if ! git diff --quiet --ignore-submodules --cached; then
        tmp="$tmp+";
    fi

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Check for unstaged changes.

    if ! git diff-files --quiet --ignore-submodules --; then
        tmp="$tmp!";
    fi

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Check for untracked files.

    if [ -n "$(git ls-files --others --exclude-standard)" ]; then
        tmp="$tmp?";
    fi

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Check for stashed files.

    if git rev-parse --verify refs/stash &>/dev/null; then
        tmp="$tmp$";
    fi

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    [ -n "$tmp" ] \
        && tmp=" [$tmp]"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    branchName="$( printf "%s" "$( git rev-parse --abbrev-ref HEAD 2> /dev/null \
        || git rev-parse --short HEAD 2> /dev/null \
        || printf " (unknown)" )" | tr -d "\n" )"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    printf "%s" "$1$branchName$tmp "

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

set_prompts() {

    local reset=$(tput sgr0 2> /dev/null)

    local cyan=""
    local emerald=""
    local green=""
    local grey=""
    local orange=""
    local pink=""
    local purple=""
    local red=""
    local white=""
    local yellow=""

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    if [ "$(tput colors 2> /dev/null || printf "0")" -ge 256 ]; then

        # Solarized colors.
        # https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized#the-values

        # Escape color literals to avoid commandline overwriting itself
        # https://stackoverflow.com/questions/2024884/commandline-overwrites-itself-when-the-commands-get-too-long#answer-9486356

        cyan="\[$(tput setaf 74)\]"
        emerald="\[$(tput setaf 70)\]"
        green="\[$(tput setaf 64)\]"
        grey="\[$(tput setaf 247)\]"
        orange="\[$(tput setaf 166)\]"
        pink="\[$(tput setaf 206)\]"
        purple="\[$(tput setaf 98)\]"
        red="\[$(tput setaf 203)\]"
        white="\[$(tput setaf 15)\]"
        yellow="\[$(tput setaf 172)\]"


    fi

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Prompt Statement variables.
    # http://ss64.com/bash/syntax-prompt.html

    # ------------------------------------------------------------------
    # | PS1 - Default interactive prompt                               |
    # ------------------------------------------------------------------

    if user_is_root; then
        # For root users

        local user_color="$red"
        local host_color="$red"
        local dir_color="$emerald"
        local prompt_color="$red"
        local prompt_value="#"

    else
        # For non-root users

        local user_color="$orange"
        local host_color="$green"
        local dir_color="$yellow"
        local prompt_color="$pink"
        local prompt_value="\$"
    fi

    PS1="\[\033]0;\W\007\]" # Terminal title (set to the
                            # current working directory)
    PS1+="\[$(tput bold)\]" # Set everything to bold from here

    case $1 in
        "")
            PS1+="$user_color\u"        # Username
            PS1+="$grey@"
            PS1+="$host_color\h"        # Host
            PS1+="$grey: "
            ;&
        "" | "mini" | "micro")
            if [ -n "$NIX_BINTOOLS" ]; then
              PS1+="$purple["
            fi
            PS1+="$dir_color\w"        # Working directory
            if [ -n "$NIX_BINTOOLS" ]; then
              PS1+="$purple]"
            fi
            PS1+=" "
            ;;
        "nano")
            if [ -n "$NIX_BINTOOLS" ]; then
              PS1+="$purple["
            fi
            PS1+="$dir_color\W"        # Basename of working directory
            if [ -n "$NIX_BINTOOLS" ]; then
              PS1+="$purple]"
            fi
            PS1+=" "
            ;;
    esac

    # Fetch git repository details
    case $1 in
        "")
            PS1+="\$(get_git_repository_details \"$grey› $cyan\")"
            ;;
        "mini" | "micro" | "nano")
            if [ "$2" = "git" ]; then
                PS1+="\$(get_git_repository_details \"$grey› $cyan\")"
            fi
            ;;
        "pico")
            if [ "$2" = "git" ]; then
                PS1+="\$(get_git_repository_details \"$grey$cyan\")"
            fi
            ;;
    esac

    PS1+="$prompt_color$prompt_value "  # Prompt

    PS1+="\[$reset\]"             # Reset everthing from here

    if [ "$1" = "micro" ]; then
        export PROMPT_DIRTRIM=2
    else
        unset PROMPT_DIRTRIM
    fi

    export PS1

    # ------------------------------------------------------------------
    # | PS2 - Continuation interactive prompt                          |
    # ------------------------------------------------------------------

    PS2="> "

    export PS2

    # ------------------------------------------------------------------
    # | PS4 - Debug prompt                                             |
    # ------------------------------------------------------------------

    # e.g:
    #
    # The GNU `date` command has the `%N` interpreted sequence while
    # other implementations don't (on macOS `gdate` can be used instead
    # of the native `date` if the `coreutils` package has been installed).
    #
    # local dateCmd=""
    #
    # if [ "$(date +%N)" != "N" ] || \
    #    [ ! -x "$(command -v "gdate")" ]; then
    #    dateCmd="date +%s.%N"
    # else
    #    dateCmd="gdate +%s.%N"
    # fi
    #
    # PS4="+$( tput cr && tput cuf 6 &&
    #          printf "$yellow %s $green%6s $reset" "$($dateCmd)" "[$LINENO]" )"
    #
    # PS4 output:
    #
    #   ++    1357074705.875970000  [123] '[' 1 == 0 ']'
    #   └──┬─┘└────┬───┘ └───┬───┘ └──┬─┘ └──────┬─────┘
    #      │       │         │        │          │
    #      │       │         │        │          └─ command
    #      │       │         │        └─ line number
    #      │       │         └─ nanoseconds
    #      │       └─ seconds since 1970-01-01 00:00:00 UTC
    #      └─ depth-level of the subshell

    PS4="+$( tput cr 2> /dev/null;
             tput cuf 6 2> /dev/null;
             printf "%s" "$reset" )"

    export PS4

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

main() {
    enable_color_support
    set_prompts "$@"
}

main "$@"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Cleanup.

unset -f enable_color_support
unset -f main
