#!/bin/bash

# Bash Variables.
# https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make `nvim` the default editor.

export EDITOR="nvim"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Set fzf preview

export FZF_PREVIEW=1

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Set default fzf command

if cmd_exists "fd"; then
    export FZF_DEFAULT_COMMAND='fd --type f --color=never'
else
    export FZF_DEFAULT_COMMAND='find * -type f'
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Change to a fuzzy found sub-directory

if cmd_exists "fd"; then
    export FZF_ALT_C_COMMAND='fd --type d . --color=never'
else
    export FZF_ALT_C_COMMAND='find * -type d'
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Append fuzzy found files to the end of the current shell command

export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Append fuzzy found files to the end of the current shell command

export FZF_DEFAULT_OPTS='
    --bind ctrl-f:page-down,ctrl-b:page-up
    --color fg+:253,bg+:237,hl+:202,hl:202
    --color info:136,prompt:136,spinner:136,pointer:7,marker:204
    --height 40% --multi --reverse'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Change to a fuzzy found sub-directory

if [ "$FZF_PREVIEW" -eq 1 ]; then
    export FZF_CTRL_T_OPTS="--preview 'bat --color=always --line-range :500 {}'"
    export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -100'"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Set git indicators in PS1

export GIT_PS1_SHOWBRANCHREMOTE=1
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM="verbose"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Ignore commands that are duplicates

export HISTCONTROL=ignoredups

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Increase the maximum number of lines of history
# persisted in the history file (default value is 500).

export HISTFILESIZE=10000

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Don't add certain commands to the history file.

export HISTIGNORE="l[sl]:[bf]g:c:clear:history:exit:q:pwd:* --help"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Increase the maximum number of commands recorded
# in the command history (default value is 500).

export HISTSIZE=10000

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Prepend $HOME/.local/share/info to INFOPATH, if not already exists

[[ ":$INFOPATH:" != *":$HOME/.local/share/info:"* ]] \
    && INFOPATH="$HOME/.local/share/info:$INFOPATH"

export INFOPATH

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Prefer US English and use UTF-8 encoding.

export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Use custom `less` colors for `man` pages.

export LESS_TERMCAP_md=$(printf "\e[1;31m")
export LESS_TERMCAP_me=$(printf "\e[0m")
export LESS_TERMCAP_se=$(printf "\e[0m")
export LESS_TERMCAP_so=$(printf "\e[1;40;92m")
export LESS_TERMCAP_ue=$(printf "\e[0m")
export LESS_TERMCAP_us=$(printf "\e[1;32m")

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Set tab width to 4.
# Highlight searches and ignore case.

export MANPAGER="less --tabs=4 --ignore-case --hilite-search --squeeze-blank-lines"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Prepend $HOME/.local/share/man to MANPATH, if not already exists

[[ ":$MANPATH:" != *":$HOME/.local/share/man:"* ]] \
    && MANPATH="$HOME/.local/share/man:$MANPATH"

export MANPATH

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Increase the maximum number of lines of history persisted
# in the `Node` REPL history file (default value is 1000).
#
# https://github.com/nodejs/node/blob/c948877688ff2b6a37f2c88724b656aae495c7b2/doc/api/repl.md#persistent-history

export NODE_REPL_HISTORY_SIZE=10000

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Prepend $HOME/bin to PATH, if not already exists

[[ ":$PATH:" != *":$HOME/bin:"* ]] \
    && PATH="$HOME/bin:${PATH}"

export PATH

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history.

export PROMPT_COMMAND="history -a;"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Set PYENV_ROOT

export PYENV_ROOT="$HOME/.pyenv"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make Python use UTF-8 encoding for output to stdin/stdout/stderr.

export PYTHONIOENCODING="UTF-8"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Set TMUXIFIER_LAYOUT_PATH

export TMUXIFIER_LAYOUT_PATH="$HOME/.config/tmuxifier"
