#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias dfh="df -h $HOME"
alias g="git"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias l="less"
alias ll="ls -laF"
alias m="man"
alias map="xargs -n1"
alias n="npm"
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias pe='pyenv'
alias p='python'
alias rmf="rm -rf"
alias v="nvim"
alias y="yarn"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# ag (The Silver Searcher)

alias ag="ag --color-line-number '0;91' --color-match '30;43' --color-path '1;36'"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# GPG

alias gpg="gpg2 --options $HOME/.gnupg/gpg.conf --options $HOME/.gnupg/gpg.conf.local"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# tmux

alias t="tmux"
alias ta="tmux attach"
alias tat="tmux attach -t"
alias tl="tmux ls"
alias tn="tmux new-session -s"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases.

. "aliases/$OS/bash_aliases"
