#!/bin/bash

# Remove all previous environment defined aliases.
unalias -a

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias aliases="alias | cut -c7- | bat -l ini --style=plain"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias dfh="df -h $HOME"
alias g="git"
alias gtop="glances"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias l="less"
alias ls="ls --color=auto"
alias ll="ls -laF"
alias m="man"
alias map="xargs -n1"
alias n="npm"
alias p='python'
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias pe='pyenv'
alias pping='prettyping --nolegend'
alias rg='rg --smart-case'
alias rmf="rm -rf"
alias v="nvim"
alias y="yarn"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# ag (The Silver Searcher)

alias ag="ag --color-line-number '0;91' --color-match '30;43' --color-path '1;36'"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# fzf

alias ff="fzf_find_edit"
alias ffg="fzf_grep_edit"

alias ga="fzf_git_add"
alias gl="fzf_git_log"
alias gpx="fzf_git_log_pickaxe"
alias gr="fzf_git_reset"
alias grf="fzf_git_reflog"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# GPG

alias gpg="gpg2 --options $HOME/.gnupg/gpg.conf --options $HOME/.gnupg/gpg.conf.local"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# tmux

alias t="tmux"
alias ta="tmux attach"
alias tat="tmux attach -t"
alias tl="tmux ls"
alias tn="tmux new-session -s"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases.

. "aliases/$OS/bash_aliases"
